### ISSUE TITLE
Heroku app deploy button throws error

### ISSUE THREAD

**Issue by oneclutteredmind** [iprobedroid/swgoh-arena-tracker#1]
Tried deploying from the readme instructions, error thrown is: "No app.json located in the repo URL provided."

I can see the file in the repo, is the correct URL being passed?

![2019-11-04](https://user-images.githubusercontent.com/4431503/68167505-8e1cde80-ff1a-11e9-8dd5-525f425833f0.png)

**Comment by iprobedroid** [comment]
must be a random error, just checked, and it worked this time

**Comment by oneclutteredmind** [comment]
It looks like it's linking to the readme file, I had to manually delete the last part of the URL to point to the master branch and that worked for me.

**Comment by StarWiiz** [comment]
can someone post right link?

**Comment by oneclutteredmind** [comment]
https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fiprobedroid%2Fswgoh-arena-tracker&template=https%3A%2F%2Fgithub.com%2Fiprobedroid%2Fswgoh-arena-tracker

That should work. I noticed that it only appends the readme if you had clicked in to the readme file manually. If you're on the home page (where the readme displays by default), the button works as intended.
