### ISSUE TITLE
Configurable sleep times

### ISSUE THREAD

**Issue by hatermater** [iprobedroid/swgoh-arena-tracker#11]
Hi,
Great work!
Can you make configurable the times in seconds to wait between each player check and after all players are checked configurable?
With your current defaults (2 sec and 3 min) if not provided. For example:
WAIT_BETWEEN_PLAYERS = 2
WAIT_AFTER_ALL_PLAYERS = 180

Thanks!
BR

**Comment by iprobedroid** [comment]
adding WAIT_BETWEEN_PLAYERS does not make sense unless you want to set it >2 sec, 2 sec is the rate limit imposed by CG, technically it is not a 2 sec wait, it is just a throttle which does not let to poll the API more frequently than once in 2 sec
WAIT_AFTER_ALL_PLAYERS is possible, maybe will do, maybe

**Comment by hatermater** [comment]
Yes. I mean to be able to increase the WAIT_BETWEEN_PLAYERS (>=2 sec, default 2 or 3 or 5 sec if not set) and increase/decrease WAIT_AFTER_ALL_PLAYERS (>=2 sec, default 180 sec if not set) depending on the situation/configuration

**Comment by iprobedroid** [comment]
what is the point to have WAIT_BETWEEN_PLAYERS > rate limit?
