### ISSUE TITLE
Discord tagging

### ISSUE THREAD

**Issue by zwichrowany** [iprobedroid/swgoh-arena-tracker#12]
Hello, is everything working with discord taging. I checked DISCORD_TAGS variable and also checked  ALLY_CODES_URL with file with players, but discord tracker isnt tagging me.

example tracker wrote : 
<@my discord id)>(my ingame name) dropped from 3 to 6
I think there is a problem with mark "<" at the beginning or im doing something wrong

I checked also another player with no discord id in gist list and tracker wrote proper tag :
@invalid-user(other ingame name) dropped from 6 to 10. There is no any "<" and ">"

**Comment by oneclutteredmind** [comment]
One thing that confused me the first time is that it's your Discord ID (not your tag, which is the @mydiscordname#1234).  It's a long numeric number, and you need to enable developer mode to access it (not as complicated as it sounds). Here's a link to the support article on how to do it (also in the README). 

https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-

**Comment by zwichrowany** [comment]
Thx for answer, in this moment i also figured that.
Lesson for me - discord id is not same as discord tag and i should read recommendations more careful.
