### ISSUE TITLE
Accept local file for ALLY_CODES_URL

### ISSUE THREAD

**Issue by hatermater** [iprobedroid/swgoh-arena-tracker#15]
Please add code to accept local file for ALLY_CODES_URL instead of requiring URL
Something like ALLY_CODES_FILE or check if file is local file first before trying network operation

**Comment by iprobedroid** [comment]
do not really understand how you going to use local files with docker containers

**Comment by hatermater** [comment]
By making a new local container (with changes) or by extracting the binaries from container and running them locally ;)

**Comment by hatermater** [comment]
Otherwise I have to run an http server to host the file in the container

**Comment by depositor** [comment]
what is the problem with using secret github gists?

**Comment by pserwe** [comment]
Personally, I'm running a standalone nginx alongside the docker containers, but there are container versions that can run essentially side by side, bound to localhost.  Gists or some other free file hosting (even discord CDN can do it if you upload the file into a chat) also works.
