### ISSUE TITLE
JSON error I dont understand

### ISSUE THREAD

**Issue by mimregi** [iprobedroid/swgoh-arena-tracker#17]
Thanks for the bot, it's fantastic!

I'm getting the following error multiple times in the log:

> [PlayerSettingsProvider]:Failed to deserialize player settings: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

I only get it when using ALLY_CODES_URL (I tested with just ALLY_CODES and a single code and it worked fine), so I assume whatever is wrong is in here:
https://gist.github.com/mimregi/1010331e0417b4593a0bec0d47a599d3

I tried it with and without the discord  ID line, tried making it public, still getting the same error.

Anything obviously not right there?

Thanks in advance!

**Comment by mimregi** [comment]
I figured it out!  Rather than delete this thread (feel free if you would prefer) I will eave it here for any other dumbass that does the same thing- I did not include ../raw at the end of the link to the file (which is totally in your instructions).

Thanks!

**Comment by mimregi** [comment]
I figured it out only to run into something else =/  Would appreciate any help, I am a bit out of my depth here.  I was troubleshooting the file but now I cannot even get a single ally code to load without incident.  See attached...
<img width="873" alt="image" src="https://user-images.githubusercontent.com/24708235/80564313-7e5af000-89bb-11ea-9961-c7b3903e5c2e.png">
<img width="842" alt="image" src="https://user-images.githubusercontent.com/24708235/80564378-a9454400-89bb-11ea-8454-0aa549e09583.png">

**Comment by iprobedroid** [comment]
yep, it should be the raw URL to gist, and you are not alone having this problem :)

**Comment by mimregi** [comment]
> ...you are not alone having this problem :)

Ha, thanks!  Definitely user error...
