### ISSUE TITLE
RQ: Ability to tag on climb

### ISSUE THREAD

**Issue by strulock** [iprobedroid/swgoh-arena-tracker#18]
Hi, and thanks for creating this - extremely useful.

We have a small set of folks that snipe our shard players on payout that we'd like to track when they climb.  Any chance we can set a variable to notify via discord on climb -or- drop?

Thank you!

**Comment by b0th5** [comment]
Vote for that too

**Comment by arman29kz** [comment]
Absolutely useless. Just change **Notifications Setting** in Discord and watch their climbing

**Comment by strulock** [comment]
Actually quite useful, unlike your comment. @arman29kz

**Comment by iprobedroid** [comment]
done
