### ISSUE TITLE
Ability to tag on fall when over X

### ISSUE THREAD

**Issue by molrakea** [iprobedroid/swgoh-arena-tracker#19]
Now that we are starting to see more GLs in arena we have many that sit it top spots all day.  They are willing to help and put in easier to beat teams but would like if they could be tagged only when a certain threshold is met, say fallen out of top 10 or top 20.

I'd be willing to help as I have some coding experience,  discord = Mol Rakea#6130

**Comment by sjefur** [comment]
I'm getting invalid user tags, while it worked before. What am I doing wrong?
