### ISSUE TITLE
Heroku stopped 

### ISSUE THREAD

**Issue by henosch** [iprobedroid/swgoh-arena-tracker#2]
How can I add your code on Linux. I don't like heroku

**Comment by depositor** [comment]
@henosch, you can use this docker image:
iprobedroid/swgoh-arena-tracker:beta-9

in dockerfile:
FROM iprobedroid/swgoh-arena-tracker:beta-9
... env variables ...
or you can use docker-compose, to set env variables

**Comment by henosch** [comment]
Hello,
I am not a developer and need a little help.
I have used git clone and docker build -f /home/henosch/swgoh-arena-tracker/Dockerfile .
Result:
Sending build context to Docker daemon  493.6kB
Step 1/4 : FROM iprobedroid/swgoh-arena-tracker:beta-9
 ---> a4cad7b59
Step 2/4 : ENV ARENA_TYPE=FLEET
 ---> Running in b22a440
Removing intermediate container b22a4407a
 ---> e266a3858027
Step 3/4 : ENV DISCORD_WEB_HOOK=https://discordapp.com/api/webhooks/6512128/M5xvLyUXdYWTj
 ---> Running in 6eeb6442
Removing intermediate container 6eeb6442
 ---> 8bb2bcad7322
Step 4/4 : ENV ALLY_CODES=123456789 
 ---> Running in 57ee535c3
Removing intermediate container 57ee535c3
 ---> 6a901f3d
Successfully built 6a901f3d

EDIT: I can run the tracker on my mac, but on raspberrypi 4 (ARMv7 Processor) I get this error:
standard_init_linux.go:211: exec user process caused "exec format error"

Can you make a arm image?
