### ISSUE TITLE
Failed to deserialize player settings

### ISSUE THREAD

**Issue by vvouvonikos** [iprobedroid/swgoh-arena-tracker#24]
Hi, I just deployed the bot on Heroku but I'm getting the following error in the application logs:
[PlayerSettingsProvider]:Failed to deserialize player settings: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
EDIT: It only happens with a json file, if I provide the allycodes in as a comma-separated list it works

**Comment by iprobedroid** [comment]
the JSON file should be properly formatted, you probably missing commas or other closing tags,
try to open the file in the editor which supports JSON(vscode for example)

**Comment by vvouvonikos** [comment]
The JSON file is properly formatted. I'm already using VS Code and used the example file. 
Until a few days ago I used the bot for my fleet shard and it was working perfectly for months. It's no more needed though so I deleted it to create one for my squad shard. And even if I use the same JSON file that I did for fleet I'm getting the same error

**Comment by iprobedroid** [comment]
what is your discord account?

**Comment by vvouvonikos** [comment]
Sorry for the late response (I'm on vacation).
My discord name is BillyTheKid#4297
