### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by zwichrowany** [iprobedroid/swgoh-arena-tracker#25]
Hello, i get this error when i try to deploy app to heroku :

A valid GitHub directory could not be found.

The given URL (https://github.com/) is not a valid GitHub repository.

**Comment by depositor** [comment]
just checked, works fine

**Comment by iprobedroid** [comment]
just checked, it works fine

**Comment by oneclutteredmind** [comment]
Make sure you are in the right spot when you launch it... I got this error when trying to launch it when I had browsed to the readme

**Comment by bdhollies** [comment]
Can further direction be provided here? Where is the correct "deploy" button? Having same problems as OP. Thanks

**Comment by iprobedroid** [comment]
https://github.com/iprobedroid/swgoh-arena-tracker

**Comment by iprobedroid** [comment]
![image](https://user-images.githubusercontent.com/51727869/94392881-19980180-01b6-11eb-9dc5-053da432a291.png)

**Comment by bdhollies** [comment]
![Screenshot 2020-09-28 182407](https://user-images.githubusercontent.com/72000846/94393639-fec68c80-01b7-11eb-992e-1ae6078632a3.png)
I get this with both the link above and the button under the Code tab

**Comment by iprobedroid** [comment]
have you tried a different browser?
or maybe this link:
https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fiprobedroid%2Fswgoh-arena-tracker&template=https%3A%2F%2Fgithub.com%2Fiprobedroid%2Fswgoh-arena-tracker

**Comment by bdhollies** [comment]
This link above worked, thank you

**Comment by iprobedroid** [comment]
which browser did you use?

**Comment by bdhollies** [comment]
Used Chrome the whole time
