### ISSUE TITLE
Request about source code

### ISSUE THREAD

**Issue by SelinaK4274** [iprobedroid/swgoh-arena-tracker#26]
Not really an issue, but since git hub doesnt allow for private messages I have no other way to reach out to you.

Like another user in february I wonder if you would be willing to share the source code of your project. Would love to have a look at how you handle things, learn a bit from it and maybe use some of it for a bit of experimenting of my own.

If you are willing I could share either an email or my discord tag or something with you for contact.

**Comment by iprobedroid** [comment]
post your discord tag here, I will contact you later

**Comment by SelinaK4274** [comment]
Thanks a lot.

**Comment by Pepiteskiller** [comment]
Hi, i'm interested too

**Comment by johninparis** [comment]
@iprobedroid I would be interested too (mainly about the API used to fetch the data). Would you please contact me too? [edit: Thank you for getting in touch!]

**Comment by iprobedroid** [comment]
@johninparis, your account does not accept friend requests

**Comment by johninparis** [comment]
Sorry about that @iprobedroid, thanks for letting me know. I just changed that setting.

**Comment by FrAcTi0N** [comment]
@iprobedroid here is mine,please contact me. Maybe both our bots can work together (I am the creator of RotBot).

**Comment by strulock** [comment]
@iprobedroid can you add me as well?

**Comment by iCeOnLy-hk** [comment]
@iprobedroid can also please have a look at the code?

**Comment by DmitryAzz** [comment]
@iprobedroid would like too, to take a look at

**Comment by tdm00** [comment]
@iprobedroid

**Comment by xelon-ua** [comment]
@iprobedroid I would like to too

**Comment by MakofBp** [comment]
@iprobedroid would like too, to take a look at source
[removed]

Thanks for sharing

**Comment by rafaeliga** [comment]
hey @iprobedroid , Im interested too, mainly to show "enemies" in the chat messages 😈

**Comment by iprobedroid** [comment]
@rafaeliga https://discord.gg/xcjvKPM, the feature to show enemies is already implemented(yet not documented), details in discord

**Comment by iprobedroid** [comment]
from now on, the code will be not shared with any new requests due to the agreement with CG
