### ISSUE TITLE
iprobedroid rank tracker not working since 11/12/2020

### ISSUE THREAD

**Issue by aljobie** [iprobedroid/swgoh-arena-tracker#31]
I use in fleet and squad arena to track.  Stopped working two days ago.  Other guild members have mentioned the same.

**Comment by iprobedroid** [comment]
join the discord for updates
reinstall it from scratch, it is fixed already

**Comment by aljobie** [comment]
i tried to join the discord channel.  I cannot find the channel. Thanks for the fix!

**Comment by iprobedroid** [comment]
the link to discord is on the main page...
https://discord.gg/xcjvKPM
