### ISSUE TITLE
Enhancement : Fleet and arena in same time

### ISSUE THREAD

**Issue by bbassac** [iprobedroid/swgoh-arena-tracker#32]
Hosting the Squad App and Fleet App on heroku is sadly impossible (app is shutdown in 15 days)
Is it possible to make working both arena type  ? With a property for fleet discord tags and squad discord tags for example

**Comment by arman29kz** [comment]
Pls read other issues before creating yours - https://github.com/iprobedroid/swgoh-arena-tracker/issues/22

**Comment by bbassac** [comment]
ok
