### ISSUE TITLE
RQ: Tag only when dropping in position

### ISSUE THREAD

**Issue by hatermater** [iprobedroid/swgoh-arena-tracker#4]
Hey,

Great work!
I have a very easy to implement request.
Now tags work always, when you climb and when you drop.
You know when you climb so you don't really need a tag, so using the tag only when dropping might be a very nice refinement and should be pretty easy to implement.

Thanks

**Comment by iprobedroid** [comment]
Hi, as far as I remember tags should work only on a drop. Currently traveling. I will double-check when I will be free.

**Comment by hatermater** [comment]
My bad
You are right.
All is good
